import Head from "next/head";
import React, { useEffect, useState } from "react";
import HomeOneMain from "../components/HomeOne/HomeOneMain";
import Footer from "../components/Layout/Footer/FooterOne/Footer";
import Header from "../components/Layout/Header/Header";

export default function Home() {
  const [number, setNumber] = useState(0);

  useEffect(() => {
    // Reset number at startup
    number = 0;
  }, []);

  return (
    <>
      <Head>
        <title>Oction - NFT Marketplace React, NextJs Template</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header HeaderStatic="oc-transparent-header" />
      <HomeOneMain />
      <Footer />
    </>
  );
}
