import Head from 'next/head';
import React from 'react';
import Header from '../components/Layout/Header/Header';
import LoginMain from '../components/Login/LoginMain';
import Footer from "../components/Layout/Footer/FooterColor/Footer";



export default function Login() {

  return (
    <>
      <Head>
        <title>Oction - NFT Marketplace React, NextJs Template</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <LoginMain />
      {/* <Footer /> */}
    </>
  )
}