import Head from 'next/head';
import React from 'react';
import SellDetailMain from '../components/SellDetail/SellDetailMain';
import Footer from "../components/Layout/Footer/FooterColor/Footer";
import Header from '../components/Layout/Header/Header';


export default function SellDetail() {

  return (
    <>
      <Head>
        <title>Oction - NFT Marketplace React, NextJs Template</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <SellDetailMain />
      <Footer />
    </>
  )
}