import Head from 'next/head';
import React from 'react';
import SettingMain from '../components/Setting/SettingMain';
import Footer from "../components/Layout/Footer/FooterColor/Footer";
import Header from '../components/Layout/Header/Header';


export default function Setting() {

  return (
    <>
      <Head>
        <title>Oction - NFT Marketplace React, NextJs Template</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <SettingMain />
      <Footer />
    </>
  )
}
